### ISSUE TITLE
test paging.c followed by run usertest.bin results in an odd memory_free call

### ISSUE THREAD

**Issue by devyn** [devyn/kit#2]
```
unmap the page
kernel/paging.c:1022(__paging_unmap_pt): invlpg (0xdeadb000)
  - ok, unmapped one page
switch back to the kernel pageset and then destroy this one
kernel/memory.c:131(memory_free): stub, pointer=0xffffffff80126000
kernel/memory.c:131(memory_free): stub, pointer=0xffffffff80124000
kernel/memory.c:131(memory_free): stub, pointer=0xffffffff80122000
kernel/memory.c:131(memory_free): stub, pointer=0xffffffff80121000
kernel/memory.c:131(memory_free): stub, pointer=0xffffffff80123000
kernel/memory.c:131(memory_free): stub, pointer=0xffffffff80127000
kernel/memory.c:131(memory_free): stub, pointer=0xffffffff80125000
  - ok
[PASS] paging.c

[2] run usertest.bin
kernel/memory.c:131(memory_free): stub, pointer=0xffffffff80127030
kernel/process.c:160(process_run):
 RAX=f00f RCX=0 RDX=ffff RBX=ffff
 RSP=7fffffffeff0 RBP=0 RSI=0 RDI=0
 R8 =0 R9 =0 R10=0 R11=0
 R12=0 R13=0 R14=0 R15=0
 RIP=4000d1
 EFLAGS=6

[3] 
```

**Comment by devyn** [comment]
Looks normal:

``` c
Breakpoint 1, memory_free_region_acquire (pages=<optimized out>, physical_base=0xffffffff80105d10) at kernel/memory.c:261
261     memory_free(node);
(gdb) backtrace
#0  memory_free_region_acquire (pages=<optimized out>, physical_base=0xffffffff80105d10) at kernel/memory.c:261
#1  0xffffffff80105ea8 in ?? ()
#2  0x0000000000400000 in ?? ()
#3  0xffffffff80105d10 in ?? ()
#4  0x0000000000000038 in ?? ()
#5  0x0000000000000007 in ?? ()
#6  0xffffffff80117aab in process_alloc (process=<optimized out>, address=<optimized out>, length=<optimized out>, flags=PAGING_READONLY) at kernel/process.c:88
#7  0x0000000000000000 in ?? ()
```
